### ISSUE TITLE
4004 webpage still points to 1.0.0 - looks like 1.1.0 was never made live on the web

### ISSUE THREAD

**Issue by scmcduffee** [AcademySoftwareFoundation/dpel-website#14]
Went to look at releasing a 1.2.0 and noticed the webpage was still at 1.0.0 in the version number presented and the data in the download is old as well.

**Comment by scmcduffee** [comment]
Uploading the 1.2 to s3 now - will change the links and description once complete

**Comment by matthewlow-dwa** [comment]
@scmcduffee , now that 1.2 is live and updated on the site, is this issue good to close?

**Comment by matthewlow-dwa** [comment]
Resolved by #15
